New structure, refactoring, name change, makefile, README update
vortexntnu/ATMEGA2560_Thruster_Interface pull request #1
Opened 2021-02-24 18:38 UTC by theBadMusician

- Created appropriate C code structure.
- Split separate functions/functionalities into respective header and source files.
- Using name ATMEGA2560_THR_INF_Firmware thoughout the repo.
- Added a makefile to compile the codebase using AVR-GCC and flash the MCU using AVRDUDE commands. (No Arduino IDE required)
- Updated README.md. Note: should be expanded with more detailed instructions in the future.

2021-02-25 13:03 UTC, oyssolbo requested changes
Impressed by the makefile! Very good! 

Mostly nitpicking on comments. You will hate me for this, but we should write strict doxygen when documenting C/C++. This makes it easier later when someone external looks through the code. Also, the pragma once should be discarded since we already use ifndef/define, and pragma once is not well-defined for C, only C++

2021-02-25 13:03 UTC, oyssolbo commented on src/Thrusters.c
> +void prearm_thruster_flood()
What does "..._flood" stand for?

2021-02-25 13:07 UTC, oyssolbo commented
And also, I'm a bit biased since I participated in writing this code

2021-02-26 16:26 UTC, theBadMusician commented
Fixed problems mentioned in the review.

2021-02-26 20:54 UTC, merged